#!/usr/bin/env python3
"""Generate slides-short.md (the 20-minute version, served by index.html) from slides.md (the full
version, served by long.html).

slides.md stays the single source: edit it, then run `python3 build_short.py` (or `npm run pdf`).
The short version moves the frames listed in MOVE to the appendix (prefixing their titles with
"Appendix · "), applies the few text edits in PATCH so that no remaining frame points to a moved
one, and rewrites the ⏱ timing markers of the speaker notes from DURATIONS.
"""
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
SEP = "\n\n---\n\n"

# Frames moved to the appendix, identified by a unique substring of their title.
MOVE = [
    "## Where are all the Icon programs?",
    "## Do LLMs invent languages?",
    "## Lesson 2: how you count changes the story",
    "## `.rpgle`: a clean extension, a biased archive",
    "## Lesson 3: an LLM judge",
    "## From case studies to a method, and back",
]

# Edits in the frames that stay, so that they do not rely on a moved frame.
PATCH = [
    ('Icon sits in the top-left cell: PLDB, Pygments and Rosetta Code had it, the LLM list did not.</p>',
     'Icon sits in the top-left cell: PLDB, Pygments and Rosetta Code had it, the LLM list did not.</p>\n'
     '<p class="smaller" style="margin-top: 0.4em"><b>Do LLMs invent languages? Rarely</b>: checking all 3,842 evidence '
     'links leaves ≈ 23 invented names (0.6%); broken evidence is far more common (appendix).</p>'),
    ("1,403 names that no upstream source has: are those real?",
     "1,403 names that no upstream source has: are those real? Almost all: after checking every evidence link "
     "(Wikipedia API, GitHub API, HTTP) and a web search on a random sample, about 23 names look invented "
     "(0.6%, at most 2%); the details are in the appendix."),
    ("this is why by-file and by-repo results disagree (part 3).",
     "this is why by-file and by-repo results disagree (appendix: \"how you count changes the story\")."),
]

# Speaking time per frame (seconds) for the 20-minute version; unknown frames get DEFAULT.
DURATIONS = [
    ("# Towards an Encyclopedia of Programming Languages Anchored", 20),
    ("## The encyclopedia today", 60),
    ("## What the encyclopedia offers", 30),
    ("## The dream:", 60),
    ("## Why now, and why it matters", 70),
    ("# 1. Four mirrors, no code", 10),
    ("## HOPL:", 40),
    ("## PL-ultimate:", 30),
    ("## PL-ultimate-llm:", 60),
    ("## Software Heritage: every extension, counted", 35),
    ("## Four mirrors, one blind spot", 40),
    ("# 2. The vision, made concrete", 10),
    ("## Languages, evidence, programs", 60),
    ("## PL, extension, program:", 70),
    ("## Two gaps, in numbers", 50),
    ("## PLI, formally:", 60),
    ("## Which language is this file in?", 60),
    ("# 3. Zoom in", 10),
    ("## One extension, all of it", 45),
    ("## Three extensions, three stories", 50),
    ("## Lesson 1:", 50),
    ("# 4. Making it real", 10),
    ("## Contributions:", 35),
    ("## Challenges:", 50),
    ("## How you can help", 40),
    ("## Catch them all!", 50),
    ("## Roadmap:", 60),
    ("# Towards an encyclopedia of programming languages anchored", 15),
]
DEFAULT = 45
MARKER = re.compile(r"⏱ T\+[\d:]+(?: \([^)]*\))? — ")


def title(frame):
    return next((l for l in frame.split("\n") if l.startswith("#")), "")


def find(frames, key):
    hits = [i for i, f in enumerate(frames) if key in title(f)]
    if len(hits) != 1:
        raise SystemExit(f"build_short.py: {len(hits)} frames match {key!r} (expected 1)")
    return hits[0]


def main():
    src = (HERE / "slides.md").read_text()
    frames = [f.strip("\n") for f in re.split(r"\n+---\n+", src)]

    moved = [frames[find(frames, k)] for k in MOVE]
    for f in moved:
        frames.remove(f)
    moved = [MARKER.sub("", re.sub(r"^## ", "## Appendix · ", f, count=1, flags=re.M)) for f in moved]
    start = next(i for i, f in enumerate(frames) if "backup-start" in f)
    frames[start + 1:start + 1] = moved

    text = SEP.join(frames)
    for old, new in PATCH:
        if old not in text:
            raise SystemExit(f"build_short.py: patch target not found: {old[:60]!r}")
        text = text.replace(old, new)
    frames = text.split(SEP)

    t = 0
    total = 0
    for i, f in enumerate(frames[:start]):
        mm, ss = divmod(t, 60)
        stamp = f"⏱ T+{mm}:{ss:02d} — "
        if "\nNote:" in f:
            head, note = f.split("\nNote:", 1)
            frames[i] = head + "\nNote: " + stamp + MARKER.sub("", note.lstrip())
        dur = next((d for k, d in DURATIONS if k in title(f)), DEFAULT)
        t += dur
        total += dur

    frames[0] = frames[0].replace("\n", "\n<!-- GENERATED by build_short.py from slides.md: edit slides.md, not this file -->\n", 1)
    (HERE / "slides-short.md").write_text(SEP.join(frames) + "\n")
    print(f"slides-short.md: {start} frames + {len(frames) - start - 1} in the appendix, "
          f"~{total // 60}:{total % 60:02d} of speaking time")


if __name__ == "__main__":
    main()
